name: S4E_CDSL_Workflow

on:
  workflow_dispatch:
  push:
    branches: [ "b_github_ci" ]
  pull_request:
    branches: [ "b_github_ci" ]

jobs:
  build:
    strategy:
      matrix:
        repo: ['bkebianyor/seal5', 'bkebianyor/etiss_wysiwyng']
    runs-on: ubuntu-latest

    steps:
    - name: Check Modified Files
      run: |
        var=$( git diff --name-only HEAD~ HEAD 2>&1) #./get_list_modified_files
        echo $var
    - name: Upload Artifacts
      uses: actions/upload-artifact@v4
      with:
        name: riscv-core-dsl-files
        path: ${{ github.workspace }}/*.core_desc   
        
    - name: Trigger Seal5 and ETISS Workflow
      uses: peter-evans/repository-dispatch@v3
      with:
        token: ${{ secrets.REPO_ACCESS_TOKEN }}
        repositry: ${{ matrix.repo }}
        event-type: s4e-cdl-event
        client-payload: '{ "trigger_repo_run_id": "${{ github.run_id }}" }'
